import { AURA_EFFECT, GAME_CONFIG, TEAM, UNIT_TAG, UNIT_TYPES, hasUnitTag } from '../data/gameConfig.js';
import { COMBAT_EVENT } from '../data/gameTypes.js';
import { MovementPolicy } from './MovementPolicy.js';
import { TargetingPolicy, gridDistance } from './TargetingPolicy.js';

const STUN_TURNS = 2;
const RELOAD_TURNS = 2;
const clamp01 = (value) => Math.max(0, Math.min(1, value));
const lerp = (start, end, progress) => start + (end - start) * progress;
const resolvedSnapshot = (unit) => ({ id: unit.id, team: unit.team, type: unit.type, row: unit.row, column: unit.column, previousRow: unit.previousRow, previousColumn: unit.previousColumn, animationStartedAt: unit.animationStartedAt, animationDuration: unit.animationDuration, hp: unit.hp, maxHp: unit.maxHp, baseWall: unit.baseWall });
const animatedSnapshot = (unit, at) => { const duration = Math.max(1, unit.animationDuration ?? 1); const progress = unit.animationStartedAt === undefined ? 1 : clamp01((at - unit.animationStartedAt) / duration); return { id: unit.id, team: unit.team, type: unit.type, row: lerp(unit.previousRow ?? unit.row, unit.row, progress), column: lerp(unit.previousColumn ?? unit.column, unit.column, progress) }; };

export class CombatActionResolver {
  constructor({ targeting = new TargetingPolicy(), movement = new MovementPolicy() } = {}) { this.targeting = targeting; this.movement = movement; this.targetPlan = null; this.resolvedFormations = new Set(); }
  auraValue(model, unit, effect, sourceTeam = unit.team) { let strongest = 0; for (const source of model.units) { if (!source.alive || source.breached || source.team !== sourceTeam) continue; const aura = UNIT_TYPES[source.type].aura; if (!aura || aura.effect !== effect || gridDistance(source, unit) > aura.range) continue; strongest = Math.max(strongest, aura.value ?? 0); } return strongest; }
  hasLivingLeader(model, team) { return model.units.some((unit) => unit.alive && !unit.breached && unit.team === team && hasUnitTag(unit.type, UNIT_TAG.LEADER)); }
  hasFormationBehavior(model, unit) { const type = UNIT_TYPES[unit.type]; if (hasUnitTag(type, UNIT_TAG.FORMATION)) return true; if (hasUnitTag(type, UNIT_TAG.FLYING) || hasUnitTag(type, UNIT_TAG.STATIONARY)) return false; return this.hasLivingLeader(model, unit.team); }
  applyStunFields(units) { for (const source of units) { if (!source.alive || source.breached) continue; const sourceType = UNIT_TYPES[source.type]; const aura = sourceType?.aura; if (!aura || aura.effect !== AURA_EFFECT.STUN) continue; const direction = source.team === TEAM.PLAYER ? 1 : -1; const affectedColumns = new Set([source.column, source.column - direction]); const canStunFlying = hasUnitTag(sourceType, UNIT_TAG.ANTI_AIR); for (const target of units) { if (!target.alive || target.team === source.team || !affectedColumns.has(target.column)) continue; if (hasUnitTag(target.type, UNIT_TAG.FLYING) && !canStunFlying) continue; target.stunTurnsRemaining = Math.max(target.stunTurnsRemaining ?? 0, STUN_TURNS); } } }
  ageStuns(units) { for (const unit of units) if ((unit.stunTurnsRemaining ?? 0) > 0) unit.stunTurnsRemaining -= 1; }
  isStunned(unit) { return (unit.stunTurnsRemaining ?? 0) > 0; }
  isReloading(unit) { return (unit.reloadTurnsRemaining ?? 0) > 0; }
  spendReloadTurn(unit) { if (!this.isReloading(unit)) return false; unit.reloadTurnsRemaining -= 1; return true; }
  beginReload(unit, type = UNIT_TYPES[unit.type]) { if (hasUnitTag(type, UNIT_TAG.RELOAD)) unit.reloadTurnsRemaining = RELOAD_TURNS; }
  attackDamage(model, attacker, consumeCharge = false) { const type = UNIT_TYPES[attacker.type]; const charging = hasUnitTag(type, UNIT_TAG.CHARGE) && !attacker.chargeUsed; if (consumeCharge && charging) attacker.chargeUsed = true; return type.attack * (charging ? 2 : 1) + this.auraValue(model, attacker, AURA_EFFECT.DAMAGE); }
  incomingDamage(model, target, damage) { return Math.max(1, damage - this.auraValue(model, target, AURA_EFFECT.SHIELD)); }
  validTargets(model, unit, type) { return model.spatialIndex.nearby(unit.row, unit.column, type.range).filter((candidate) => candidate.alive && candidate.team !== unit.team && this.targeting.canTarget(unit, candidate, type)); }
  buildTargetPlan(model, units) { const plan = new Map(); for (const unit of units) { if (!unit.alive || unit.breached || this.isStunned(unit) || this.isReloading(unit)) { plan.set(unit.id, null); continue; } const type = UNIT_TYPES[unit.type]; const nearby = model.spatialIndex.nearby(unit.row, unit.column, type.range); if (hasUnitTag(type, UNIT_TAG.HEAL)) { const allies = nearby.filter((candidate) => candidate.alive && candidate.team === unit.team && candidate.id !== unit.id && candidate.hp < candidate.maxHp && this.targeting.isInAttackPattern(unit, candidate, type)); plan.set(unit.id, this.targeting.nearest(allies, unit)?.id ?? null); continue; } if (type.attack <= 0 && !hasUnitTag(type, UNIT_TAG.PUSH) && !hasUnitTag(type, UNIT_TAG.FACTORY)) { plan.set(unit.id, null); continue; } const enemies = nearby.filter((candidate) => candidate.alive && candidate.team !== unit.team && this.targeting.canTarget(unit, candidate, type)); if (hasUnitTag(type, UNIT_TAG.SALVO)) plan.set(unit.id, enemies.map((enemy) => enemy.id)); else plan.set(unit.id, this.targeting.nearest(enemies, unit)?.id ?? null); } return plan; }
  processQueue(model, units, now, duration) { const queue = units.slice(); let consecutivePasses = 0; this.applyStunFields(units); this.resolvedFormations.clear(); this.targetPlan = model.spatialIndex ? this.buildTargetPlan(model, units) : null; try { while (queue.length > 0 && consecutivePasses < queue.length) { const unit = queue.shift(); if (!unit.alive) continue; if (this.processUnit(model, unit, now, duration)) consecutivePasses = 0; else { queue.push(unit); consecutivePasses += 1; } } } finally { this.targetPlan = null; this.resolvedFormations.clear(); this.ageStuns(units); } }
  processUnit(model, unit, now, duration) { if (!unit.alive) return true; unit.stunnedThisTick = this.isStunned(unit); if (unit.stunnedThisTick) return true; const type = UNIT_TYPES[unit.type]; const reloading = this.spendReloadTurn(unit); if (hasUnitTag(type, UNIT_TAG.FLYING)) return this.processFlyingUnit(model, unit, type, now, duration, reloading); if (!reloading && hasUnitTag(type, UNIT_TAG.FACTORY) && this.tryProduceUnit(model, unit, type, now)) return true; if (!reloading && this.tryCombatAction(model, unit, type, now, duration)) return true; if (hasUnitTag(type, UNIT_TAG.STATIONARY)) return true; if (!reloading && this.shouldPassForIncomingTarget(model, unit, type)) return true; if (this.hasFormationBehavior(model, unit)) return this.processFormationMovement(model, unit, now, duration); unit.movedThisTurn = this.movement.move(model, unit, now, duration); if (!unit.movedThisTurn) return reloading || hasUnitTag(type, UNIT_TAG.STATIONARY); if (!reloading && hasUnitTag(type, UNIT_TAG.FAST_ATTACK)) this.tryCombatAction(model, unit, type, now, duration); return true; }
  processFormationMovement(model, unit, now, duration) { if (this.resolvedFormations.has(unit.team)) return true; const formation = model.units.filter((candidate) => candidate.alive && !candidate.breached && candidate.team === unit.team && this.hasFormationBehavior(model, candidate)); const memberHasAction = formation.some((member) => { const planned = this.targetPlan?.get(member.id); return Array.isArray(planned) ? planned.length > 0 : planned !== null && planned !== undefined; }); this.resolvedFormations.add(unit.team); if (memberHasAction || formation.some((member) => this.isStunned(member))) return true; const moved = this.movement.moveFormation(model, formation, now, duration); for (const member of formation) member.movedThisTurn = moved; return true; }
  processFlyingUnit(model, unit, type, now, duration, reloading = false) { unit.movedThisTurn = this.movement.move(model, unit, now, duration); if (!reloading) this.tryCombatAction(model, unit, type, now, duration); return true; }
  canActAfterMovement(unit, type = UNIT_TYPES[unit.type]) { return !unit.movedThisTurn || hasUnitTag(type, UNIT_TAG.FAST_ATTACK) || hasUnitTag(type, UNIT_TAG.FLYING); }
  plannedTarget(model, unit) { if (!this.targetPlan?.has(unit.id)) return undefined; const targetId = this.targetPlan.get(unit.id); if (targetId === null || Array.isArray(targetId)) return targetId; return model.units.find((candidate) => candidate.id === targetId && candidate.alive) ?? null; }
  plannedTargets(model, unit) { if (!this.targetPlan?.has(unit.id)) return undefined; const targetIds = this.targetPlan.get(unit.id); if (!Array.isArray(targetIds)) return undefined; const idSet = new Set(targetIds); return model.units.filter((candidate) => candidate.alive && idSet.has(candidate.id)); }
  shouldPassForIncomingTarget(model, unit, type) { if (type.range <= 1 || !this.targetPlan?.has(unit.id)) return false; const planned = this.targetPlan.get(unit.id); if (Array.isArray(planned) ? planned.length > 0 : planned !== null) return false; return model.units.some((enemy) => { if (!enemy.alive || enemy.team === unit.team || enemy.breached || enemy.previousRow === undefined || enemy.previousColumn === undefined) return false; if (enemy.row === enemy.previousRow && enemy.column === enemy.previousColumn) return false; if (!this.targeting.canTarget(unit, enemy, type)) return false; const previousPosition = { ...enemy, row: enemy.previousRow, column: enemy.previousColumn }; return !this.targeting.canTarget(unit, previousPosition, type); }); }
  tryProduceUnit(model, unit, type, now) { const production = type.production; if (!production) return false; if ((unit.productionCooldown ?? 0) > 0) { unit.productionCooldown -= 1; return true; } const direction = unit.team === TEAM.PLAYER ? 1 : -1; const row = unit.row; const column = unit.column + direction; if (column < 0 || column >= GAME_CONFIG.columns || model.occupantAt(row, column)) return true; const produced = model.unitFactory.create({ row, column, type: production.type }, unit.team, model.nextUnitId++, now); model.units.push(produced); model.spatialIndex.add(produced); unit.productionCooldown = production.interval; return true; }
  tryCombatAction(model, unit, type, now, duration) { if (!this.canActAfterMovement(unit, type)) return false; const plannedTarget = this.plannedTarget(model, unit); const hasPlan = plannedTarget !== undefined; if (hasUnitTag(type, UNIT_TAG.HEAL)) { const target = hasPlan ? plannedTarget : this.targeting.nearest(model.spatialIndex.nearby(unit.row, unit.column, type.range).filter((ally) => ally.alive && ally.team === unit.team && ally.id !== unit.id && ally.hp < ally.maxHp && this.targeting.isInAttackPattern(unit, ally, type)), unit); if (!target || target.hp >= target.maxHp) return false; const healed = Math.min(type.healAmount, target.maxHp - target.hp); target.hp += healed; model.emitCombatEvent({ type: COMBAT_EVENT.UNIT_HEALED, source: resolvedSnapshot(unit), target: resolvedSnapshot(target), amount: healed, at: now }); return true; } if (hasUnitTag(type, UNIT_TAG.SALVO)) { const targets = this.plannedTargets(model, unit) ?? this.validTargets(model, unit, type); if (!targets.length) return false; for (const target of targets) if (target.alive) this.attackUnit(model, unit, target, now, duration); this.beginReload(unit, type); return true; } const target = hasPlan ? plannedTarget : this.targeting.nearest(this.validTargets(model, unit, type), unit); if (!target) return false; if (hasUnitTag(type, UNIT_TAG.PUSH)) return this.pushUnit(model, unit, target, now, duration); if (type.attack <= 0) return false; if (hasUnitTag(type, UNIT_TAG.BOMB)) this.detonate(model, unit, now, duration); else this.attackUnit(model, unit, target, now, duration); this.beginReload(unit, type); return true; }
  pushUnit(model, attacker, target, now, duration) { const direction = attacker.team === TEAM.PLAYER ? 1 : -1; const nextColumn = target.column + direction; if (nextColumn < 0 || nextColumn >= GAME_CONFIG.columns || model.occupantAt(target.row, nextColumn)) return true; const targetBefore = resolvedSnapshot(target); const attackerPreviousRow = attacker.row; const attackerPreviousColumn = attacker.column; const targetPreviousRow = target.row; const targetPreviousColumn = target.column; model.spatialIndex.remove(attacker); model.spatialIndex.remove(target); target.column = nextColumn; target.previousRow = targetPreviousRow; target.previousColumn = targetPreviousColumn; target.animationStartedAt = now; target.animationDuration = duration; attacker.row = targetPreviousRow; attacker.column = targetPreviousColumn; attacker.previousRow = attackerPreviousRow; attacker.previousColumn = attackerPreviousColumn; attacker.animationStartedAt = now; attacker.animationDuration = duration; attacker.movedThisTurn = true; model.spatialIndex.add(target); model.spatialIndex.add(attacker); model.emitCombatEvent({ type: COMBAT_EVENT.UNIT_PUSHED, source: resolvedSnapshot(attacker), target: targetBefore, unit: resolvedSnapshot(target), at: now }); return true; }
  tryAgileDodge(model, attacker, target, now, duration) { if (!hasUnitTag(target.type, UNIT_TAG.AGILE) || target.agileDodgeUsed) return false; target.agileDodgeUsed = true; const openRows = [target.row - 1, target.row + 1].filter((row) => row >= 0 && row < GAME_CONFIG.rows && !model.occupantAt(row, target.column)); if (openRows.length === 0) return false; const previousRow = target.row; const previousColumn = target.column; target.row = openRows[Math.floor(model.random() * openRows.length)]; target.previousRow = previousRow; target.previousColumn = previousColumn; target.animationStartedAt = now; target.animationDuration = duration; model.spatialIndex.move(target, previousRow, previousColumn); model.emitCombatEvent({ type: COMBAT_EVENT.UNIT_DODGED, attacker: resolvedSnapshot(attacker), target: { ...resolvedSnapshot(target), row: previousRow, column: previousColumn }, unit: resolvedSnapshot(target), at: now }); return true; }
  destroyUnit(model, unit, now, duration) { if (!unit.alive) return; if (unit.baseWall) { model.damageBaseWall(unit, unit.hp, now); return; } if (hasUnitTag(unit.type, UNIT_TAG.BOMB)) this.detonate(model, unit, now, duration); else model.killUnit(unit, now, duration); }
  applyDamage(model, source, target, rawDamage, eventType, now, duration) { const damage = this.incomingDamage(model, target, rawDamage); if (target.baseWall) model.damageBaseWall(target, damage, now); else target.hp -= damage; const event = eventType === COMBAT_EVENT.UNIT_ATTACKED ? { type: eventType, attacker: resolvedSnapshot(source), target: resolvedSnapshot(target), damage, range: UNIT_TYPES[source.type].range, at: now } : { type: eventType, source: resolvedSnapshot(source), target: resolvedSnapshot(target), damage, at: now }; model.emitCombatEvent(event); if (target.alive && target.hp <= 0) this.destroyUnit(model, target, now, duration); return damage; }
  detonate(model, attacker, now, duration) { if (!attacker.alive) return; const source = animatedSnapshot(attacker, now); const rawDamage = this.attackDamage(model, attacker); const victims = model.units.filter((unit) => unit.alive && unit.team !== attacker.team && gridDistance(attacker, unit) <= 1); attacker.alive = false; model.spatialIndex.remove(attacker); model.emitCombatEvent({ type: COMBAT_EVENT.UNIT_DETONATED, unit: source, at: now }); for (const victim of victims) { if (!victim.alive) continue; const damage = this.incomingDamage(model, victim, rawDamage); if (victim.baseWall) model.damageBaseWall(victim, damage, now); else victim.hp -= damage; model.emitCombatEvent({ type: COMBAT_EVENT.SPLASH_HIT, source, target: resolvedSnapshot(victim), damage, at: now }); if (victim.hp <= 0) this.destroyUnit(model, victim, now, duration); } }
  reflectThorns(model, attacker, target, damage, now, duration) { const type = UNIT_TYPES[target.type]; if (!hasUnitTag(type, UNIT_TAG.THORNS) || UNIT_TYPES[attacker.type].range !== 1 || !attacker.alive) return; const ratio = type.thorns?.reflectRatio ?? 0.5; const reflectedDamage = this.incomingDamage(model, attacker, Math.max(1, Math.ceil(damage * ratio))); attacker.hp -= reflectedDamage; if (attacker.hp <= 0) this.destroyUnit(model, attacker, now, duration); }
  attackUnit(model, attacker, target, enemiesOrNow, nowOrDuration, legacyDuration) { const legacyCall = Array.isArray(enemiesOrNow); const now = legacyCall ? nowOrDuration : enemiesOrNow; const duration = legacyCall ? legacyDuration : nowOrDuration; const rawDamage = this.attackDamage(model, attacker, true); if (this.tryAgileDodge(model, attacker, target, now, duration)) return; const damage = this.applyDamage(model, attacker, target, rawDamage, COMBAT_EVENT.UNIT_ATTACKED, now, duration); this.reflectThorns(model, attacker, target, damage, now, duration); if (hasUnitTag(attacker.type, UNIT_TAG.AOE)) { const enemies = model.units.filter((enemy) => enemy.alive && enemy.team !== attacker.team); for (const enemy of enemies) { if (enemy.id === target.id || gridDistance(target, enemy) > 1 || enemy.baseWall) continue; const splashDamage = this.incomingDamage(model, enemy, rawDamage); enemy.hp -= splashDamage; model.emitCombatEvent({ type: COMBAT_EVENT.SPLASH_HIT, source: resolvedSnapshot(attacker), target: resolvedSnapshot(enemy), damage: splashDamage, at: now }); if (enemy.hp <= 0) this.destroyUnit(model, enemy, now, duration); } } }
}
